### ISSUE TITLE
Add wlroots virtual keyboard protocol

### ISSUE THREAD

**Issue by Jaakkonen** [vially/wayland-explorer#1]
https://github.com/swaywm/wlroots/blob/master/protocol/virtual-keyboard-unstable-v1.xml
Virtual keyboard protocol from wlroots does not show up in wayland.app. Maybe this is caused by it not having the `wlr-` prefix

**Comment by vially** [comment]
Previously all the Wayland protocols were coming from either [wayland-protocols](https://github.com/wayland-project/wayland-protocols) or the [wlr-protocols](https://github.com/swaywm/wlr-protocols) repositories.

So as long as the protocols are published to either one of these two repositories it should be relatively easy to pick them up (e.g.: update the [submodules](https://github.com/vially/wayland-explorer/tree/2f02f8316c91bb9d3c55a70c37534a9955a60218/protocols) and run `yarn regenerate-protocols`).

However, [virtual-keyboard-unstable](https://github.com/swaywm/wlroots/blob/master/protocol/virtual-keyboard-unstable-v1.xml) isn't yet part of those repositories and that's why it was not in the list of supported protocols. It looks like it was actually [proposed for inclusion](https://lists.freedesktop.org/archives/wayland-devel/2019-September/040882.html) into `wayland-protocols` but I'm not sure why it wasn't accepted.

In any case, supporting protocols that are not part of those two repositories is a valid use-case so I just went ahead and added support for it (2f02f8316c91bb9d3c55a70c37534a9955a60218): https://wayland.app/protocols/virtual-keyboard-unstable-v1

**Comment by vially** [comment]
> [...] here is [the most deployed and used wayland object interface](https://review.tizen.org/git/?p=platform/core/uifw/wayland-extension.git;a=blob;f=protocol/tizen-extension.xml;h=7bacfa6dbf1f54a74f83fe3a27bca38419397dde;hb=refs/heads/accepted/tizen_common). Notice how that isn’t mentioned here or elsewhere

Regarding @letoram's comment on [lobste.rs](https://lobste.rs/s/0xkm30/wayland_explorer#c_rpoolg) (I don't have an account so I can't reply there), see my comment above for a much more mundane explanation for that.

**Comment by letoram** [comment]
If you want one I can send you an invite :-)

The point there is not towards your project specifically (sans the assumed conspiracy, though that was somewhat in jest), it is the more general situation - that there is a substantial mass of definitions that you have to treasure hunt for and the set of "what is Wayland" is a very loosely defined one.

**Comment by vially** [comment]
> If you want one I can send you an invite :-)

I just managed to open an account and [replied on there too](https://lobste.rs/s/0xkm30/wayland_explorer#c_xviqlq) (hence deleting my previous comment in here). I did actually consider asking you for an invite though :smile:.

> there is a substantial mass of definitions that you have to treasure hunt for and the set of "what is Wayland" is a very loosely defined one

I definitely agree and that's why I started this project in the first place. Although I did kind of stop halfway there when maybe I should have spent more time hunting these protocols down, but as you say, that's not always easy.
