### ISSUE TITLE
It does not properly link to things from other protocols

### ISSUE THREAD

**Issue by wb9688** [vially/wayland-explorer#6]
For example when on https://wayland.app/protocols/wlr-output-management-unstable-v1 I click on "wl_output.transform", it links to https://wayland.app/protocols/wlr-output-management-unstable-v1#wl_output:enum:transform instead of https://wayland.app/protocols/wayland#wl_output:enum:transform

**Comment by bbb651** [comment]
This seems hard to solve in the general case, as the protocol itself does not specify which protocol an interface/enum is from and it can theoretically be from any other protocol. Practically speaking the vast majority of cases they are going to be from the wayland core protocol because everything implicitly depends on it, xdg-shell being a particularly rough example, I'm not even sure if there is an instance of this elsewhere (although with `ext-image-capture-source-v1` and `ext-image-copy-capture-v1` it will be more common).

I think the proper way to solve this is at compile time, I think due to protocols changing relatively slow it's fine to keep converter a single step, and use the other protocols potentially before they are updated right? Worst case rerunning the converter twice always guarantees links are correct - we can even verify the links and automatically reconvert if needed.

**Comment by WhyNotHugo** [comment]
`ext-image-capture-source` is already published and also has a link which points to a non-core interface:

https://wayland.app/protocols/ext-image-capture-source-v1#ext_foreign_toplevel_handle_v1

**Comment by bbb651** [comment]
I've got a proof of concept working for linking at compile time:

![image](https://github.com/user-attachments/assets/0e6a88c9-8cc3-4b01-abb3-7ba6e9bf933e)

![image](https://github.com/user-attachments/assets/55a3cae2-bad4-4ed6-9a93-fbd4a23c4ecf)

![image](https://github.com/user-attachments/assets/6b55c024-a11a-4753-b2f9-e4d426e02b33)
(simulated failure)

![image](https://github.com/user-attachments/assets/7b65f131-ed09-43a9-827a-0d8e1421237c)

And I finally got it to work:
![image](https://github.com/user-attachments/assets/85bc4a82-13fd-4056-8c9e-320c33d1b8c4)


The need to figure out the source of truth for protcol page ids (and potentially merge them), currently the `protocol.name`, `protocol-registry.ts` ids and protocol json filename can all be different, I need to clean it up a lot, and port it to `regenerate-protocols-data.ts` as currently it only works with `convert-wayland-xml-to-json.ts`.

**Comment by WhyNotHugo** [comment]
Thanks!
